#!/bin/bash

function print_bash_completion()
{
cat << "EOF"

_tabssh_words=()

function _tabssh_read_config()
{
	local _tabssh_config=~/.tabssh
	local serverName
	while read line
	do
		serverName=$(echo $line | cut -d' ' -f1) 
		_tabssh_words+=("$serverName")
	done < ${_tabssh_config}
}

function _tabssh_completion()
{
	if [[ "${#COMP_WORDS[@]}" != "2" ]]; then
		return
	fi

	if [[ ${#_tabssh_words[@]} -eq 0 ]]; then
		_tabssh_read_config
	fi

	COMPREPLY=($(compgen -W "${_tabssh_words[*]}" "${COMP_WORDS[1]}"))
}

complete -F _tabssh_completion tabssh
EOF
}

function usage()
{
	echo -e "Usage: \n\t$(basename $0) [user@host | completion]"
	echo
	echo -e 'Notes: \n\tThe completion reads ~/.tabssh file that contains'
	echo -e '\tuser@host each line.'
}

############################ main ##########################
case $1 in
"completion")
	print_bash_completion
	exit
	;;
"")
	usage
	exit
	;;
*)
	tmux new-window -n $1 ssh $1
	;;
esac
